// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69AESBPw7O1GV077PLktuiQBx1-oDTdM',
    appId: '1:153126438486:web:c88ec1b041cbd566f21df7',
    messagingSenderId: '153126438486',
    projectId: 'hamro-dokan-6f4be',
    authDomain: 'hamro-dokan-6f4be.firebaseapp.com',
    storageBucket: 'hamro-dokan-6f4be.firebasestorage.app',
    measurementId: 'G-RMLVGME40S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHhy9oCcyAs45Hm0ld58g_PpSuMBZOMlY',
    appId: '1:153126438486:android:65d9871404966b68f21df7',
    messagingSenderId: '153126438486',
    projectId: 'hamro-dokan-6f4be',
    storageBucket: 'hamro-dokan-6f4be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjcgZxOVt-SMwaV_JUoT01Zmw6XpyORjA',
    appId: '1:153126438486:ios:e0a165446640a10bf21df7',
    messagingSenderId: '153126438486',
    projectId: 'hamro-dokan-6f4be',
    storageBucket: 'hamro-dokan-6f4be.firebasestorage.app',
    androidClientId: '153126438486-0pupavc7l972i6cku2dmu60en1en1sdu.apps.googleusercontent.com',
    iosClientId: '153126438486-apu7qocqett8p3bfvbeejlat0rfo5eba.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyypc4MyqBBneptEWpF17u3s7cu8X4wIY',
    appId: '1:823307041176:ios:7b67fa8db6b2840d0653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    databaseURL: 'https://codingwitht-c6d0f-default-rtdb.firebaseio.com',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
    androidClientId: '823307041176-kun16mo723tugpbptbcbupndhaubv8cn.apps.googleusercontent.com',
    iosClientId: '823307041176-lp36pj2a155ifcmkeil3p2ch72krur3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC69AESBPw7O1GV077PLktuiQBx1-oDTdM',
    appId: '1:153126438486:web:1d04313b960a1329f21df7',
    messagingSenderId: '153126438486',
    projectId: 'hamro-dokan-6f4be',
    authDomain: 'hamro-dokan-6f4be.firebaseapp.com',
    storageBucket: 'hamro-dokan-6f4be.firebasestorage.app',
    measurementId: 'G-JML9MMDQ1F',
  );

}